'use client'

import {
  createContext, useContext, useState, useCallback, useEffect, ReactNode,
} from 'react'
import { fetchEventos, patchEvento, insertEvento } from '@/services/eventosDB'
import { Evento, StatusEvento, TipoOperador } from '@/types'
import { useToast } from './ToastContext'

export interface ImportResult {
  criados: number
  existentes: number
  erros: number
}

export interface EventosContextValue {
  eventos: Evento[]
  loading: boolean
  error: string | null
  processarEvento: (eventoId: string, diligenciaId: string) => void
  arquivarEvento: (eventoId: string) => void
  importarSimulados: () => Promise<ImportResult>
}

// ─── Demandas simuladas (como se tivessem chegado por e-mail) ─────────────────

const DEMANDAS_SIMULADAS: Omit<Evento, 'id' | 'createdAt'>[] = [
  {
    ccc: 'BR-2026040063',
    dataEvento: '2026-04-10',
    horaEvento: '14:30',
    dataRecebimento: '2026-04-10',
    horaRecebimento: '16:00',
    operacao: TipoOperador.Proprio,
    empresa: 'Uber do Brasil Tecnologia Ltda',
    segmento: 'Transporte de Passageiros',
    tipoEvento: 'Roubo com Violência',
    nivelAgressao: 3,
    motoristaAgredido: true,
    nomeVitima: 'João Carlos Pereira dos Santos',
    cargoVitima: 'Motorista',
    telefoneVitima: '11987654321',
    cidade: 'São Paulo',
    uf: 'SP',
    gtsc: 'GTSC-SP-001',
    statusEvento: StatusEvento.Pendente,
    diligenciaId: undefined,
  },
  {
    ccc: 'BR-2026040071',
    dataEvento: '2026-04-15',
    horaEvento: '09:15',
    dataRecebimento: '2026-04-15',
    horaRecebimento: '11:00',
    operacao: TipoOperador.Proprio,
    empresa: '99 Tecnologia Ltda',
    segmento: 'Motorista por App',
    tipoEvento: 'Furto de Pertences',
    nivelAgressao: 1,
    motoristaAgredido: false,
    nomeVitima: 'Rodrigo Almeida Costa',
    cargoVitima: 'Motorista',
    telefoneVitima: '19998765432',
    cidade: 'Campinas',
    uf: 'SP',
    gtsc: 'GTSC-SP-002',
    statusEvento: StatusEvento.Pendente,
    diligenciaId: undefined,
  },
  {
    ccc: 'BR-2026040085',
    dataEvento: '2026-04-18',
    horaEvento: '18:45',
    dataRecebimento: '2026-04-18',
    horaRecebimento: '19:30',
    operacao: TipoOperador.Terceirizado,
    empresa: 'iFood — Logística e Entrega',
    segmento: 'Entrega por App',
    tipoEvento: 'Agressão Física',
    nivelAgressao: 2,
    motoristaAgredido: true,
    nomeVitima: 'Patricia Lima Rodrigues',
    cargoVitima: 'Entregadora',
    telefoneVitima: '31987651234',
    cidade: 'Belo Horizonte',
    uf: 'MG',
    gtsc: 'GTSC-MG-001',
    statusEvento: StatusEvento.Pendente,
    diligenciaId: undefined,
  },
  {
    ccc: 'BR-2026040094',
    dataEvento: '2026-04-22',
    horaEvento: '11:00',
    dataRecebimento: '2026-04-22',
    horaRecebimento: '12:00',
    operacao: TipoOperador.Terceirizado,
    empresa: 'Rappi Brasil S.A.',
    segmento: 'Entrega por App',
    tipoEvento: 'Acidente de Trânsito',
    nivelAgressao: 1,
    motoristaAgredido: false,
    nomeVitima: 'Marcelo Vieira Santos',
    cargoVitima: 'Entregador',
    telefoneVitima: '21976543210',
    cidade: 'Rio de Janeiro',
    uf: 'RJ',
    gtsc: 'GTSC-RJ-001',
    statusEvento: StatusEvento.Pendente,
    diligenciaId: undefined,
  },
  {
    ccc: 'BR-2026040107',
    dataEvento: '2026-04-25',
    horaEvento: '08:30',
    dataRecebimento: '2026-04-25',
    horaRecebimento: '09:00',
    operacao: TipoOperador.Agregado,
    empresa: 'Loggi Tecnologia S.A.',
    segmento: 'Logística e Distribuição',
    tipoEvento: 'Ameaça com Arma de Fogo',
    nivelAgressao: 3,
    motoristaAgredido: true,
    nomeVitima: 'Carlos Eduardo Mendes',
    cargoVitima: 'Motorista',
    telefoneVitima: '41998765432',
    cidade: 'Curitiba',
    uf: 'PR',
    gtsc: 'GTSC-PR-001',
    statusEvento: StatusEvento.Pendente,
    diligenciaId: undefined,
  },
  {
    ccc: 'BR-2026040115',
    dataEvento: '2026-04-02',
    horaEvento: '22:10',
    dataRecebimento: '2026-04-03',
    horaRecebimento: '08:00',
    operacao: TipoOperador.Proprio,
    empresa: 'Uber do Brasil Tecnologia Ltda',
    segmento: 'Transporte de Passageiros',
    tipoEvento: 'Sequestro Relâmpago',
    nivelAgressao: 3,
    motoristaAgredido: true,
    nomeVitima: 'Fernando Augusto Neves',
    cargoVitima: 'Motorista',
    telefoneVitima: '11991234567',
    cidade: 'Guarulhos',
    uf: 'SP',
    gtsc: 'GTSC-SP-003',
    statusEvento: StatusEvento.Pendente,
    diligenciaId: undefined,
  },
  {
    ccc: 'BR-2026040122',
    dataEvento: '2026-04-03',
    horaEvento: '13:50',
    dataRecebimento: '2026-04-03',
    horaRecebimento: '15:20',
    operacao: TipoOperador.Terceirizado,
    empresa: 'Mercado Livre Tecnologia Ltda',
    segmento: 'Logística e Distribuição',
    tipoEvento: 'Furto do Veículo',
    nivelAgressao: 2,
    motoristaAgredido: false,
    nomeVitima: 'Andressa Karla Souza',
    cargoVitima: 'Motorista',
    telefoneVitima: '71992345678',
    cidade: 'Salvador',
    uf: 'BA',
    gtsc: 'GTSC-BA-001',
    statusEvento: StatusEvento.Pendente,
    diligenciaId: undefined,
  },
  {
    ccc: 'BR-2026040130',
    dataEvento: '2026-04-04',
    horaEvento: '07:20',
    dataRecebimento: '2026-04-04',
    horaRecebimento: '08:45',
    operacao: TipoOperador.Agregado,
    empresa: 'DHL Express Brasil Ltda',
    segmento: 'Logística e Distribuição',
    tipoEvento: 'Roubo com Violência',
    nivelAgressao: 3,
    motoristaAgredido: true,
    nomeVitima: 'Edson Roberto Freitas',
    cargoVitima: 'Motorista',
    telefoneVitima: '85993456789',
    cidade: 'Fortaleza',
    uf: 'CE',
    gtsc: 'GTSC-CE-001',
    statusEvento: StatusEvento.Pendente,
    diligenciaId: undefined,
  },
  {
    ccc: 'BR-2026040141',
    dataEvento: '2026-04-05',
    horaEvento: '16:00',
    dataRecebimento: '2026-04-05',
    horaRecebimento: '17:30',
    operacao: TipoOperador.Proprio,
    empresa: '99 Tecnologia Ltda',
    segmento: 'Motorista por App',
    tipoEvento: 'Assédio e Ameaça Verbal',
    nivelAgressao: 1,
    motoristaAgredido: false,
    nomeVitima: 'Tatiane Cristina Borges',
    cargoVitima: 'Motorista',
    telefoneVitima: '81994567890',
    cidade: 'Recife',
    uf: 'PE',
    gtsc: 'GTSC-PE-001',
    statusEvento: StatusEvento.Pendente,
    diligenciaId: undefined,
  },
  {
    ccc: 'BR-2026040156',
    dataEvento: '2026-04-06',
    horaEvento: '20:30',
    dataRecebimento: '2026-04-07',
    horaRecebimento: '09:00',
    operacao: TipoOperador.Proprio,
    empresa: 'Cabify do Brasil S.A.',
    segmento: 'Transporte de Passageiros',
    tipoEvento: 'Agressão Física',
    nivelAgressao: 2,
    motoristaAgredido: true,
    nomeVitima: 'Leonardo Prado Assunção',
    cargoVitima: 'Motorista',
    telefoneVitima: '62995678901',
    cidade: 'Goiânia',
    uf: 'GO',
    gtsc: 'GTSC-GO-001',
    statusEvento: StatusEvento.Pendente,
    diligenciaId: undefined,
  },
  {
    ccc: 'BR-2026040163',
    dataEvento: '2026-04-07',
    horaEvento: '11:45',
    dataRecebimento: '2026-04-07',
    horaRecebimento: '13:00',
    operacao: TipoOperador.Terceirizado,
    empresa: 'Lalamove do Brasil Ltda',
    segmento: 'Logística e Distribuição',
    tipoEvento: 'Acidente de Trânsito',
    nivelAgressao: 2,
    motoristaAgredido: true,
    nomeVitima: 'Gustavo Henrique Teixeira',
    cargoVitima: 'Motorista',
    telefoneVitima: '92996789012',
    cidade: 'Manaus',
    uf: 'AM',
    gtsc: 'GTSC-AM-001',
    statusEvento: StatusEvento.Pendente,
    diligenciaId: undefined,
  },
  {
    ccc: 'BR-2026040178',
    dataEvento: '2026-04-08',
    horaEvento: '06:15',
    dataRecebimento: '2026-04-08',
    horaRecebimento: '07:30',
    operacao: TipoOperador.Agregado,
    empresa: 'iFood — Logística e Entrega',
    segmento: 'Entrega de Alimentos',
    tipoEvento: 'Tentativa de Roubo',
    nivelAgressao: 2,
    motoristaAgredido: false,
    nomeVitima: 'Silvana Moura Cardoso',
    cargoVitima: 'Entregadora',
    telefoneVitima: '91997890123',
    cidade: 'Belém',
    uf: 'PA',
    gtsc: 'GTSC-PA-001',
    statusEvento: StatusEvento.Pendente,
    diligenciaId: undefined,
  },
  {
    ccc: 'BR-2026040185',
    dataEvento: '2026-04-09',
    horaEvento: '19:00',
    dataRecebimento: '2026-04-09',
    horaRecebimento: '20:15',
    operacao: TipoOperador.Proprio,
    empresa: 'Uber do Brasil Tecnologia Ltda',
    segmento: 'Transporte de Passageiros',
    tipoEvento: 'Furto de Pertences',
    nivelAgressao: 1,
    motoristaAgredido: false,
    nomeVitima: 'Renata Oliveira Fonseca',
    cargoVitima: 'Motorista',
    telefoneVitima: '48998901234',
    cidade: 'Florianópolis',
    uf: 'SC',
    gtsc: 'GTSC-SC-001',
    statusEvento: StatusEvento.Pendente,
    diligenciaId: undefined,
  },
  {
    ccc: 'BR-2026040192',
    dataEvento: '2026-04-11',
    horaEvento: '15:30',
    dataRecebimento: '2026-04-11',
    horaRecebimento: '16:45',
    operacao: TipoOperador.Terceirizado,
    empresa: 'Rappi Brasil S.A.',
    segmento: 'Entrega de Alimentos',
    tipoEvento: 'Vandalismo ao Veículo',
    nivelAgressao: 1,
    motoristaAgredido: false,
    nomeVitima: 'Diego Martins Leal',
    cargoVitima: 'Entregador',
    telefoneVitima: '51999012345',
    cidade: 'Porto Alegre',
    uf: 'RS',
    gtsc: 'GTSC-RS-001',
    statusEvento: StatusEvento.Pendente,
    diligenciaId: undefined,
  },
  {
    ccc: 'BR-2026040205',
    dataEvento: '2026-04-12',
    horaEvento: '10:00',
    dataRecebimento: '2026-04-12',
    horaRecebimento: '11:00',
    operacao: TipoOperador.Proprio,
    empresa: 'Loggi Tecnologia S.A.',
    segmento: 'Logística e Distribuição',
    tipoEvento: 'Ameaça com Arma de Fogo',
    nivelAgressao: 3,
    motoristaAgredido: true,
    nomeVitima: 'Wellington Cruz Barbosa',
    cargoVitima: 'Motoboy',
    telefoneVitima: '21990123456',
    cidade: 'Nova Iguaçu',
    uf: 'RJ',
    gtsc: 'GTSC-RJ-002',
    statusEvento: StatusEvento.Pendente,
    diligenciaId: undefined,
  },
  {
    ccc: 'BR-2026040213',
    dataEvento: '2026-04-13',
    horaEvento: '23:45',
    dataRecebimento: '2026-04-14',
    horaRecebimento: '07:00',
    operacao: TipoOperador.Agregado,
    empresa: '99 Tecnologia Ltda',
    segmento: 'Motorista por App',
    tipoEvento: 'Roubo com Violência',
    nivelAgressao: 3,
    motoristaAgredido: true,
    nomeVitima: 'Marcos Antônio Ribeiro',
    cargoVitima: 'Motorista',
    telefoneVitima: '11981234567',
    cidade: 'Santo André',
    uf: 'SP',
    gtsc: 'GTSC-SP-001',
    statusEvento: StatusEvento.Pendente,
    diligenciaId: undefined,
  },
  {
    ccc: 'BR-2026040224',
    dataEvento: '2026-04-14',
    horaEvento: '08:00',
    dataRecebimento: '2026-04-14',
    horaRecebimento: '09:30',
    operacao: TipoOperador.Proprio,
    empresa: 'iFood — Logística e Entrega',
    segmento: 'Entrega de Alimentos',
    tipoEvento: 'Acidente de Trânsito',
    nivelAgressao: 2,
    motoristaAgredido: true,
    nomeVitima: 'Amanda Cristina Nunes',
    cargoVitima: 'Entregadora',
    telefoneVitima: '31982345678',
    cidade: 'Contagem',
    uf: 'MG',
    gtsc: 'GTSC-MG-002',
    statusEvento: StatusEvento.Pendente,
    diligenciaId: undefined,
  },
  {
    ccc: 'BR-2026040237',
    dataEvento: '2026-04-16',
    horaEvento: '17:20',
    dataRecebimento: '2026-04-16',
    horaRecebimento: '18:00',
    operacao: TipoOperador.Terceirizado,
    empresa: 'Amazon Transportes Ltda',
    segmento: 'Logística e Distribuição',
    tipoEvento: 'Furto do Veículo',
    nivelAgressao: 2,
    motoristaAgredido: false,
    nomeVitima: 'Paulo Sérgio Cavalcante',
    cargoVitima: 'Motorista',
    telefoneVitima: '41983456789',
    cidade: 'São José dos Pinhais',
    uf: 'PR',
    gtsc: 'GTSC-PR-001',
    statusEvento: StatusEvento.Pendente,
    diligenciaId: undefined,
  },
  {
    ccc: 'BR-2026040248',
    dataEvento: '2026-04-17',
    horaEvento: '12:10',
    dataRecebimento: '2026-04-17',
    horaRecebimento: '13:30',
    operacao: TipoOperador.Proprio,
    empresa: 'Cabify do Brasil S.A.',
    segmento: 'Transporte de Passageiros',
    tipoEvento: 'Assédio e Ameaça Verbal',
    nivelAgressao: 1,
    motoristaAgredido: false,
    nomeVitima: 'Juliana Ferreira Campos',
    cargoVitima: 'Motorista',
    telefoneVitima: '85984567890',
    cidade: 'Caucaia',
    uf: 'CE',
    gtsc: 'GTSC-CE-001',
    statusEvento: StatusEvento.Pendente,
    diligenciaId: undefined,
  },
  {
    ccc: 'BR-2026040259',
    dataEvento: '2026-04-19',
    horaEvento: '21:00',
    dataRecebimento: '2026-04-20',
    horaRecebimento: '08:00',
    operacao: TipoOperador.Agregado,
    empresa: 'Loggi Tecnologia S.A.',
    segmento: 'Mototaxi por App',
    tipoEvento: 'Agressão Física',
    nivelAgressao: 2,
    motoristaAgredido: true,
    nomeVitima: 'Roberto Silva Dantas',
    cargoVitima: 'Motoboy',
    telefoneVitima: '71985678901',
    cidade: 'Feira de Santana',
    uf: 'BA',
    gtsc: 'GTSC-BA-001',
    statusEvento: StatusEvento.Pendente,
    diligenciaId: undefined,
  },
  {
    ccc: 'BR-2026040266',
    dataEvento: '2026-04-20',
    horaEvento: '14:45',
    dataRecebimento: '2026-04-20',
    horaRecebimento: '16:00',
    operacao: TipoOperador.Proprio,
    empresa: 'Uber do Brasil Tecnologia Ltda',
    segmento: 'Transporte de Passageiros',
    tipoEvento: 'Lesão Corporal Culposa',
    nivelAgressao: 2,
    motoristaAgredido: false,
    nomeVitima: 'Cláudia Regina Pinto',
    cargoVitima: 'Passageira',
    telefoneVitima: '81986789012',
    cidade: 'Olinda',
    uf: 'PE',
    gtsc: 'GTSC-PE-001',
    statusEvento: StatusEvento.Pendente,
    diligenciaId: undefined,
  },
  {
    ccc: 'BR-2026040274',
    dataEvento: '2026-04-21',
    horaEvento: '07:30',
    dataRecebimento: '2026-04-21',
    horaRecebimento: '08:45',
    operacao: TipoOperador.Terceirizado,
    empresa: 'Mercado Livre Tecnologia Ltda',
    segmento: 'Logística e Distribuição',
    tipoEvento: 'Roubo com Violência',
    nivelAgressao: 3,
    motoristaAgredido: true,
    nomeVitima: 'Thiago Henrique Gomes',
    cargoVitima: 'Motorista',
    telefoneVitima: '62987890123',
    cidade: 'Aparecida de Goiânia',
    uf: 'GO',
    gtsc: 'GTSC-GO-001',
    statusEvento: StatusEvento.Pendente,
    diligenciaId: undefined,
  },
  {
    ccc: 'BR-2026040281',
    dataEvento: '2026-04-23',
    horaEvento: '16:30',
    dataRecebimento: '2026-04-23',
    horaRecebimento: '17:15',
    operacao: TipoOperador.Proprio,
    empresa: 'iFood — Logística e Entrega',
    segmento: 'Entrega de Alimentos',
    tipoEvento: 'Tentativa de Roubo',
    nivelAgressao: 2,
    motoristaAgredido: false,
    nomeVitima: 'Bruna Aparecida Lopes',
    cargoVitima: 'Entregadora',
    telefoneVitima: '11978901234',
    cidade: 'Osasco',
    uf: 'SP',
    gtsc: 'GTSC-SP-002',
    statusEvento: StatusEvento.Pendente,
    diligenciaId: undefined,
  },
  {
    ccc: 'BR-2026040293',
    dataEvento: '2026-04-24',
    horaEvento: '10:15',
    dataRecebimento: '2026-04-24',
    horaRecebimento: '11:30',
    operacao: TipoOperador.Agregado,
    empresa: 'DHL Express Brasil Ltda',
    segmento: 'Logística e Distribuição',
    tipoEvento: 'Furto de Pertences',
    nivelAgressao: 1,
    motoristaAgredido: false,
    nomeVitima: 'Fábio Luiz Monteiro',
    cargoVitima: 'Motorista',
    telefoneVitima: '51979012345',
    cidade: 'Canoas',
    uf: 'RS',
    gtsc: 'GTSC-RS-001',
    statusEvento: StatusEvento.Pendente,
    diligenciaId: undefined,
  },
  {
    ccc: 'BR-2026040301',
    dataEvento: '2026-04-26',
    horaEvento: '13:00',
    dataRecebimento: '2026-04-26',
    horaRecebimento: '14:20',
    operacao: TipoOperador.Proprio,
    empresa: 'Rappi Brasil S.A.',
    segmento: 'Entrega de Alimentos',
    tipoEvento: 'Acidente de Trânsito',
    nivelAgressao: 1,
    motoristaAgredido: true,
    nomeVitima: 'Natalia Souza Ferreira',
    cargoVitima: 'Entregadora',
    telefoneVitima: '21970123456',
    cidade: 'Duque de Caxias',
    uf: 'RJ',
    gtsc: 'GTSC-RJ-001',
    statusEvento: StatusEvento.Pendente,
    diligenciaId: undefined,
  },
  {
    ccc: 'BR-2026040315',
    dataEvento: '2026-04-27',
    horaEvento: '19:50',
    dataRecebimento: '2026-04-28',
    horaRecebimento: '07:30',
    operacao: TipoOperador.Terceirizado,
    empresa: 'Lalamove do Brasil Ltda',
    segmento: 'Logística e Distribuição',
    tipoEvento: 'Ameaça com Arma de Fogo',
    nivelAgressao: 3,
    motoristaAgredido: true,
    nomeVitima: 'Alexandre Rocha Pereira',
    cargoVitima: 'Motorista',
    telefoneVitima: '31961234567',
    cidade: 'Uberlândia',
    uf: 'MG',
    gtsc: 'GTSC-MG-001',
    statusEvento: StatusEvento.Pendente,
    diligenciaId: undefined,
  },
  {
    ccc: 'BR-2026040328',
    dataEvento: '2026-04-28',
    horaEvento: '09:40',
    dataRecebimento: '2026-04-28',
    horaRecebimento: '10:30',
    operacao: TipoOperador.Proprio,
    empresa: 'Uber do Brasil Tecnologia Ltda',
    segmento: 'Transporte de Passageiros',
    tipoEvento: 'Furto de Pertences',
    nivelAgressao: 1,
    motoristaAgredido: false,
    nomeVitima: 'Priscila Andrade Monteiro',
    cargoVitima: 'Motorista',
    telefoneVitima: '11962345678',
    cidade: 'São Bernardo do Campo',
    uf: 'SP',
    gtsc: 'GTSC-SP-003',
    statusEvento: StatusEvento.Pendente,
    diligenciaId: undefined,
  },
  {
    ccc: 'BR-2026040337',
    dataEvento: '2026-04-29',
    horaEvento: '22:30',
    dataRecebimento: '2026-04-30',
    horaRecebimento: '08:00',
    operacao: TipoOperador.Agregado,
    empresa: '99 Tecnologia Ltda',
    segmento: 'Mototaxi por App',
    tipoEvento: 'Roubo com Violência',
    nivelAgressao: 3,
    motoristaAgredido: true,
    nomeVitima: 'Henrique Alves Cardozo',
    cargoVitima: 'Motoboy',
    telefoneVitima: '48963456789',
    cidade: 'Joinville',
    uf: 'SC',
    gtsc: 'GTSC-SC-001',
    statusEvento: StatusEvento.Pendente,
    diligenciaId: undefined,
  },
  {
    ccc: 'BR-2026040346',
    dataEvento: '2026-04-30',
    horaEvento: '15:10',
    dataRecebimento: '2026-04-30',
    horaRecebimento: '16:00',
    operacao: TipoOperador.Terceirizado,
    empresa: 'Amazon Transportes Ltda',
    segmento: 'Logística e Distribuição',
    tipoEvento: 'Vandalismo ao Veículo',
    nivelAgressao: 1,
    motoristaAgredido: false,
    nomeVitima: 'Cristiane Batista Nobre',
    cargoVitima: 'Motorista',
    telefoneVitima: '92964567890',
    cidade: 'Manaus',
    uf: 'AM',
    gtsc: 'GTSC-AM-001',
    statusEvento: StatusEvento.Pendente,
    diligenciaId: undefined,
  },
  {
    ccc: 'BR-2026050358',
    dataEvento: '2026-05-01',
    horaEvento: '11:20',
    dataRecebimento: '2026-05-01',
    horaRecebimento: '12:00',
    operacao: TipoOperador.Proprio,
    empresa: 'Cabify do Brasil S.A.',
    segmento: 'Transporte de Passageiros',
    tipoEvento: 'Agressão Física',
    nivelAgressao: 2,
    motoristaAgredido: true,
    nomeVitima: 'Rafael Correia Lima',
    cargoVitima: 'Motorista',
    telefoneVitima: '62975678901',
    cidade: 'Goiânia',
    uf: 'GO',
    gtsc: 'GTSC-GO-001',
    statusEvento: StatusEvento.Pendente,
    diligenciaId: undefined,
  },
]

const EventosContext = createContext<EventosContextValue | null>(null)

export function EventosProvider({ children }: { children: ReactNode }) {
  const [eventos, setEventos] = useState<Evento[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const { addToast } = useToast()

  useEffect(() => {
    fetchEventos()
      .then((data) => { setEventos(data); setLoading(false) })
      .catch((err) => {
        console.error('[EventosContext] fetch:', err)
        setError('Não foi possível carregar os eventos.')
        setLoading(false)
      })
  }, [])

  const processarEvento = useCallback((eventoId: string, diligenciaId: string) => {
    setEventos((prev) =>
      prev.map((e) =>
        e.id === eventoId ? { ...e, statusEvento: StatusEvento.Criado, diligenciaId } : e
      )
    )
    patchEvento(eventoId, { status_evento: StatusEvento.Criado, diligencia_id: diligenciaId })
      .catch((err) => { console.error(err); addToast('error', 'Não foi possível atualizar o evento.') })
  }, [addToast])

  const arquivarEvento = useCallback((eventoId: string) => {
    setEventos((prev) =>
      prev.map((e) => e.id === eventoId ? { ...e, statusEvento: StatusEvento.Arquivado } : e)
    )
    patchEvento(eventoId, { status_evento: StatusEvento.Arquivado })
      .catch((err) => { console.error(err); addToast('error', 'Não foi possível arquivar o evento.') })
  }, [addToast])

  const importarSimulados = useCallback(async (): Promise<ImportResult> => {
    let criados = 0
    let existentes = 0
    let erros = 0

    for (const ev of DEMANDAS_SIMULADAS) {
      // Deduplicação por CCC
      const jaTem = eventos.some((e) => e.ccc === ev.ccc)
      if (jaTem) { existentes++; continue }

      try {
        const novo = await insertEvento(ev)
        setEventos((prev) => [novo, ...prev])
        criados++
      } catch (err) {
        console.error('[importarSimulados] falhou para', ev.ccc, err)
        erros++
      }
    }

    return { criados, existentes, erros }
  }, [eventos])

  return (
    <EventosContext.Provider value={{ eventos, loading, error, processarEvento, arquivarEvento, importarSimulados }}>
      {children}
    </EventosContext.Provider>
  )
}

export function useEventos(): EventosContextValue {
  const ctx = useContext(EventosContext)
  if (!ctx) throw new Error('useEventos fora do EventosProvider')
  return ctx
}
